# Generated by Django 5.0.6 on 2024-07-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorcado_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahorcado',
            name='mensaje',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
