# Generated by Django 5.0.6 on 2024-07-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorcado_game', '0003_alter_ahorcado_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahorcado',
            name='letras_adivinadas',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
