# Generated by Django 5.0.6 on 2024-07-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorcado_game', '0004_alter_ahorcado_letras_adivinadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahorcado',
            name='palabra_secreta',
            field=models.CharField(default='', max_length=50),
        ),
    ]
