# Generated by Django 5.0.6 on 2024-07-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorcado_game', '0005_alter_ahorcado_palabra_secreta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahorcado',
            name='intentos_restantes',
            field=models.IntegerField(default=6),
        ),
    ]
